RandomForest:
  max_depth:
  - 10
  - 20
  - 30
  min_samples_leaf:
  - 1
  - 2
  min_samples_split:
  - 2
  - 5
  n_estimators:
  - 100
  - 200
  - 300
RandomForestBest:
  max_depth: 30
  min_samples_leaf: 2
  min_samples_split: 5
  n_estimators: 300
XGBoost:
  colsample_bytree:
  - 0.7
  - 0.8
  - 1.0
  learning_rate:
  - 0.05
  - 0.1
  - 0.2
  max_depth:
  - 6
  - 8
  - 10
  n_estimators:
  - 200
  - 300
  subsample:
  - 0.7
  - 0.8
  - 1.0
XGBoostBest:
  colsample_bytree: 1.0
  learning_rate: 0.2
  max_depth: 6
  n_estimators: 200
  subsample: 0.7
