COLUMNS:
  bankrupt?: int64
  roa(c)_before_interest_and_depreciation_before_interest: float64
  roa(a)_before_interest_and_%_after_tax: float64
  roa(b)_before_interest_and_depreciation_after_tax: float64
  operating_gross_margin: float64
  realized_sales_gross_margin: float64
  operating_profit_rate: float64
  pre-tax_net_interest_rate: float64
  after-tax_net_interest_rate: float64
  non-industry_income_and_expenditure/revenue: float64
  continuous_interest_rate_(after_tax): float64
  operating_expense_rate: float64
  research_and_development_expense_rate: float64
  cash_flow_rate: float64
  interest-bearing_debt_interest_rate: float64
  tax_rate_(a): float64
  net_value_per_share_(b): float64
  net_value_per_share_(a): float64
  net_value_per_share_(c): float64
  persistent_eps_in_the_last_four_seasons: float64
  cash_flow_per_share: float64
  revenue_per_share: float64
  operating_profit_per_share: float64
  per_share_net_profit_before_tax: float64
  realized_sales_gross_profit_growth_rate: float64
  operating_profit_growth_rate: float64
  after-tax_net_profit_growth_rate: float64
  regular_net_profit_growth_rate: float64
  continuous_net_profit_growth_rate: float64
  total_asset_growth_rate: float64
  net_value_growth_rate: float64
  total_asset_return_growth_rate_ratio: float64
  cash_reinvestment_%: float64
  current_ratio: float64
  quick_ratio: float64
  interest_expense_ratio: float64
  total_debt/total_net_worth: float64
  debt_ratio_%: float64
  net_worth/assets: float64
  long-term_fund_suitability_ratio_(a): float64
  borrowing_dependency: float64
  contingent_liabilities/net_worth: float64
  operating_profit/paid-in_capital: float64
  net_profit_before_tax/paid-in_capital: float64
  inventory_and_accounts_receivable/net_value: float64
  total_asset_turnover: float64
  accounts_receivable_turnover: float64
  average_collection_days: float64
  inventory_turnover_rate_(times): float64
  fixed_assets_turnover_frequency: float64
  net_worth_turnover_rate_(times): float64
  revenue_per_person: float64
  operating_profit_per_person: float64
  allocation_rate_per_person: float64
  working_capital_to_total_assets: float64
  quick_assets/total_assets: float64
  current_assets/total_assets: float64
  cash/total_assets: float64
  quick_assets/current_liability: float64
  cash/current_liability: float64
  current_liability_to_assets: float64
  operating_funds_to_liability: float64
  inventory/working_capital: float64
  inventory/current_liability: float64
  current_liabilities/liability: float64
  working_capital/equity: float64
  current_liabilities/equity: float64
  long-term_liability_to_current_assets: float64
  retained_earnings_to_total_assets: float64
  total_income/total_expense: float64
  total_expense/assets: float64
  current_asset_turnover_rate: float64
  quick_asset_turnover_rate: float64
  working_capital_turnover_rate: float64
  cash_turnover_rate: float64
  cash_flow_to_sales: float64
  fixed_assets_to_assets: float64
  current_liability_to_liability: float64
  current_liability_to_equity: float64
  equity_to_long-term_liability: float64
  cash_flow_to_total_assets: float64
  cash_flow_to_liability: float64
  cfo_to_assets: float64
  cash_flow_to_equity: float64
  current_liability_to_current_assets: float64
  liability-assets_flag: int64
  net_income_to_total_assets: float64
  total_assets_to_gnp_price: float64
  no-credit_interval: float64
  gross_profit_to_sales: float64
  net_income_to_stockholder's_equity: float64
  liability_to_equity: float64
  degree_of_financial_leverage_(dfl): float64
  interest_coverage_ratio_(interest_expense_to_ebit): float64
  net_income_flag: int64
  equity_to_liability: float64

TARGET_COLUMN:
  name: bankrupt?
