artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/forest cover type.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/covtype.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/covtype.csv

model_train:
  root_dir: artifacts/model_train
  train_data_path: artifacts/data_transformation/dataset_train.csv
  validation_data_path: artifacts/data_transformation/dataset_validation.csv
  test_data_path: artifacts/data_transformation/dataset_test.csv
  model_name: model.joblib
